sudo: true
language: java
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
## gpg stuff
before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
# code climate configure
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
## default build
script: mvn --settings .travis/settings.xml -U clean install
# code climate upload coverage
after_script:
  - "sed -e 's/<[\/]\?group[^>]*>//g' ./coverage/target/site/jacoco-aggregate/jacoco.xml > ./coverage/site/jacoco-aggregate/jacoco-cc.xml"
  - "JACOCO_SOURCE_PATH='commons-auth-adapter/src/main/java commons-auth-api/src/main/java commons-auth-core/src/main/java commons-auth-email-postmark/src/main/java commons-auth-email-smtp/src/main/java commons-auth-forms/src/main/java commons-auth-jpa/src/main/java commons-auth-jpa/target/generated-sources/annotations commons-auth-mongo/src/main/java commons-auth-server/src/main/java commons-auth-service/src/main/java commons-auth-test/src/main/java' ./cc-test-reporter format-coverage -t jacoco ./coverage/target/site/jacoco-aggregate/jacoco-cc.xml"
  - "./cc-test-reporter upload-coverage"
## release on tag
deploy:
  - provider: script
    script: ".travis/deploy.sh"
    skip_cleanup: true
    on:
      tags: true