spring:
  # database connection
  data:
    mongodb:
      database: commons-auth-sample
  # json configuration
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      INDENT_OUTPUT: true
    default-property-inclusion: NON_NULL
  # email
  mail:
    host: smtp.mailgun.org
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    port: 587

logging:
  level:
    io.rocketbase: TRACE



# auth configuration
auth:
  jwt:
    secret: 'cmFiRmZ5RThJc2pjMzBONVE3dnczbW1mb3puRjhnaGRYeFA3NmpRa0JGa2x3Qk1JZXVKRjJBZVFidW1vNzZOZg=='